/**
 * 標準化錯誤類型和分類系統
 * 定義錯誤碼、等級和類別
 */

/**
 * 錯誤嚴重程度等級
 */
export const ERROR_SEVERITY = {
  LOW: 'low',           // 輕微錯誤，不影響核心功能
  MEDIUM: 'medium',     // 中等錯誤，影響部分功能
  HIGH: 'high',         // 嚴重錯誤，影響核心功能
  CRITICAL: 'critical'  // 致命錯誤，系統無法正常運行
};

/**
 * 錯誤類型分類
 */
export const ERROR_TYPES = {
  VALIDATION: 'validation',         // 驗證錯誤
  AUTHENTICATION: 'authentication', // 認證錯誤
  AUTHORIZATION: 'authorization',   // 授權錯誤
  NOT_FOUND: 'not_found',          // 資源未找到
  CONFLICT: 'conflict',            // 資源衝突
  RATE_LIMIT: 'rate_limit',        // 速率限制
  EXTERNAL_SERVICE: 'external_service', // 外部服務錯誤
  DATABASE: 'database',            // 資料庫錯誤
  SYSTEM: 'system',               // 系統錯誤
  NETWORK: 'network',             // 網路錯誤
  TIMEOUT: 'timeout',             // 超時錯誤
  UNKNOWN: 'unknown'              // 未知錯誤
};

/**
 * 錯誤碼定義
 */
export const ERROR_CODES = {
  // 驗證錯誤 (4000-4099)
  VALIDATION_FAILED: 'E4000',
  INVALID_INPUT: 'E4001',
  MISSING_REQUIRED_FIELD: 'E4002',
  INVALID_FORMAT: 'E4003',
  INPUT_TOO_LONG: 'E4004',
  INPUT_TOO_SHORT: 'E4005',
  INVALID_PARAMETER: 'E4006',

  // 認證錯誤 (4010-4019)
  AUTHENTICATION_FAILED: 'E4010',
  INVALID_CREDENTIALS: 'E4011',
  TOKEN_EXPIRED: 'E4012',
  TOKEN_INVALID: 'E4013',
  SESSION_EXPIRED: 'E4014',

  // 授權錯誤 (4030-4039)
  AUTHORIZATION_FAILED: 'E4030',
  INSUFFICIENT_PERMISSIONS: 'E4031',
  ACCESS_DENIED: 'E4032',

  // 資源錯誤 (4040-4049)
  RESOURCE_NOT_FOUND: 'E4040',
  ENDPOINT_NOT_FOUND: 'E4041',
  FILE_NOT_FOUND: 'E4042',

  // 衝突錯誤 (4090-4099)
  RESOURCE_CONFLICT: 'E4090',
  DUPLICATE_ENTRY: 'E4091',
  OPERATION_CONFLICT: 'E4092',

  // 速率限制 (4290-4299)
  RATE_LIMIT_EXCEEDED: 'E4290',
  TOO_MANY_REQUESTS: 'E4291',
  REQUEST_QUOTA_EXCEEDED: 'E4292',

  // 系統錯誤 (5000-5099)
  INTERNAL_SERVER_ERROR: 'E5000',
  SERVICE_UNAVAILABLE: 'E5001',
  CONFIGURATION_ERROR: 'E5002',
  MAINTENANCE_MODE: 'E5003',

  // 資料庫錯誤 (5100-5199)
  DATABASE_CONNECTION_FAILED: 'E5100',
  DATABASE_QUERY_FAILED: 'E5101',
  DATABASE_TRANSACTION_FAILED: 'E5102',
  DATABASE_CONSTRAINT_VIOLATION: 'E5103',
  DATABASE_TIMEOUT: 'E5104',

  // 外部服務錯誤 (5200-5299)
  EXTERNAL_SERVICE_ERROR: 'E5200',
  GEMINI_CLI_ERROR: 'E5201',
  GEMINI_CLI_TIMEOUT: 'E5202',
  GEMINI_CLI_NOT_AVAILABLE: 'E5203',
  GEMINI_CLI_AUTH_FAILED: 'E5204',
  GEMINI_CLI_RATE_LIMITED: 'E5205',

  // 網路錯誤 (5300-5399)
  NETWORK_ERROR: 'E5300',
  CONNECTION_TIMEOUT: 'E5301',
  CONNECTION_REFUSED: 'E5302',
  DNS_RESOLUTION_FAILED: 'E5303',

  // WebSocket 錯誤 (5400-5499)
  WEBSOCKET_CONNECTION_FAILED: 'E5400',
  WEBSOCKET_SEND_FAILED: 'E5401',
  WEBSOCKET_AUTHENTICATION_FAILED: 'E5402',

  // 未知錯誤 (9999)
  UNKNOWN_ERROR: 'E9999'
};

/**
 * 錯誤碼到錯誤類型的映射
 */
export const ERROR_CODE_TO_TYPE = {
  // 驗證錯誤
  [ERROR_CODES.VALIDATION_FAILED]: ERROR_TYPES.VALIDATION,
  [ERROR_CODES.INVALID_INPUT]: ERROR_TYPES.VALIDATION,
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: ERROR_TYPES.VALIDATION,
  [ERROR_CODES.INVALID_FORMAT]: ERROR_TYPES.VALIDATION,
  [ERROR_CODES.INPUT_TOO_LONG]: ERROR_TYPES.VALIDATION,
  [ERROR_CODES.INPUT_TOO_SHORT]: ERROR_TYPES.VALIDATION,
  [ERROR_CODES.INVALID_PARAMETER]: ERROR_TYPES.VALIDATION,

  // 認證錯誤
  [ERROR_CODES.AUTHENTICATION_FAILED]: ERROR_TYPES.AUTHENTICATION,
  [ERROR_CODES.INVALID_CREDENTIALS]: ERROR_TYPES.AUTHENTICATION,
  [ERROR_CODES.TOKEN_EXPIRED]: ERROR_TYPES.AUTHENTICATION,
  [ERROR_CODES.TOKEN_INVALID]: ERROR_TYPES.AUTHENTICATION,
  [ERROR_CODES.SESSION_EXPIRED]: ERROR_TYPES.AUTHENTICATION,

  // 授權錯誤
  [ERROR_CODES.AUTHORIZATION_FAILED]: ERROR_TYPES.AUTHORIZATION,
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: ERROR_TYPES.AUTHORIZATION,
  [ERROR_CODES.ACCESS_DENIED]: ERROR_TYPES.AUTHORIZATION,

  // 資源錯誤
  [ERROR_CODES.RESOURCE_NOT_FOUND]: ERROR_TYPES.NOT_FOUND,
  [ERROR_CODES.ENDPOINT_NOT_FOUND]: ERROR_TYPES.NOT_FOUND,
  [ERROR_CODES.FILE_NOT_FOUND]: ERROR_TYPES.NOT_FOUND,

  // 衝突錯誤
  [ERROR_CODES.RESOURCE_CONFLICT]: ERROR_TYPES.CONFLICT,
  [ERROR_CODES.DUPLICATE_ENTRY]: ERROR_TYPES.CONFLICT,
  [ERROR_CODES.OPERATION_CONFLICT]: ERROR_TYPES.CONFLICT,

  // 速率限制
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: ERROR_TYPES.RATE_LIMIT,
  [ERROR_CODES.TOO_MANY_REQUESTS]: ERROR_TYPES.RATE_LIMIT,
  [ERROR_CODES.REQUEST_QUOTA_EXCEEDED]: ERROR_TYPES.RATE_LIMIT,

  // 系統錯誤
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: ERROR_TYPES.SYSTEM,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: ERROR_TYPES.SYSTEM,
  [ERROR_CODES.CONFIGURATION_ERROR]: ERROR_TYPES.SYSTEM,
  [ERROR_CODES.MAINTENANCE_MODE]: ERROR_TYPES.SYSTEM,

  // 資料庫錯誤
  [ERROR_CODES.DATABASE_CONNECTION_FAILED]: ERROR_TYPES.DATABASE,
  [ERROR_CODES.DATABASE_QUERY_FAILED]: ERROR_TYPES.DATABASE,
  [ERROR_CODES.DATABASE_TRANSACTION_FAILED]: ERROR_TYPES.DATABASE,
  [ERROR_CODES.DATABASE_CONSTRAINT_VIOLATION]: ERROR_TYPES.DATABASE,
  [ERROR_CODES.DATABASE_TIMEOUT]: ERROR_TYPES.DATABASE,

  // 外部服務錯誤
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: ERROR_TYPES.EXTERNAL_SERVICE,
  [ERROR_CODES.GEMINI_CLI_ERROR]: ERROR_TYPES.EXTERNAL_SERVICE,
  [ERROR_CODES.GEMINI_CLI_TIMEOUT]: ERROR_TYPES.EXTERNAL_SERVICE,
  [ERROR_CODES.GEMINI_CLI_NOT_AVAILABLE]: ERROR_TYPES.EXTERNAL_SERVICE,
  [ERROR_CODES.GEMINI_CLI_AUTH_FAILED]: ERROR_TYPES.EXTERNAL_SERVICE,
  [ERROR_CODES.GEMINI_CLI_RATE_LIMITED]: ERROR_TYPES.EXTERNAL_SERVICE,

  // 網路錯誤
  [ERROR_CODES.NETWORK_ERROR]: ERROR_TYPES.NETWORK,
  [ERROR_CODES.CONNECTION_TIMEOUT]: ERROR_TYPES.TIMEOUT,
  [ERROR_CODES.CONNECTION_REFUSED]: ERROR_TYPES.NETWORK,
  [ERROR_CODES.DNS_RESOLUTION_FAILED]: ERROR_TYPES.NETWORK,

  // WebSocket 錯誤
  [ERROR_CODES.WEBSOCKET_CONNECTION_FAILED]: ERROR_TYPES.SYSTEM,
  [ERROR_CODES.WEBSOCKET_SEND_FAILED]: ERROR_TYPES.SYSTEM,
  [ERROR_CODES.WEBSOCKET_AUTHENTICATION_FAILED]: ERROR_TYPES.AUTHENTICATION,

  // 未知錯誤
  [ERROR_CODES.UNKNOWN_ERROR]: ERROR_TYPES.UNKNOWN
};

/**
 * 錯誤碼到嚴重程度的映射
 */
export const ERROR_CODE_TO_SEVERITY = {
  // 低嚴重程度
  [ERROR_CODES.INVALID_INPUT]: ERROR_SEVERITY.LOW,
  [ERROR_CODES.INVALID_FORMAT]: ERROR_SEVERITY.LOW,
  [ERROR_CODES.INPUT_TOO_LONG]: ERROR_SEVERITY.LOW,
  [ERROR_CODES.INPUT_TOO_SHORT]: ERROR_SEVERITY.LOW,
  [ERROR_CODES.RESOURCE_NOT_FOUND]: ERROR_SEVERITY.LOW,
  [ERROR_CODES.ENDPOINT_NOT_FOUND]: ERROR_SEVERITY.LOW,

  // 中等嚴重程度
  [ERROR_CODES.VALIDATION_FAILED]: ERROR_SEVERITY.MEDIUM,
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: ERROR_SEVERITY.MEDIUM,
  [ERROR_CODES.INVALID_PARAMETER]: ERROR_SEVERITY.MEDIUM,
  [ERROR_CODES.AUTHENTICATION_FAILED]: ERROR_SEVERITY.MEDIUM,
  [ERROR_CODES.AUTHORIZATION_FAILED]: ERROR_SEVERITY.MEDIUM,
  [ERROR_CODES.RESOURCE_CONFLICT]: ERROR_SEVERITY.MEDIUM,
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: ERROR_SEVERITY.MEDIUM,
  [ERROR_CODES.GEMINI_CLI_AUTH_FAILED]: ERROR_SEVERITY.MEDIUM,
  [ERROR_CODES.GEMINI_CLI_RATE_LIMITED]: ERROR_SEVERITY.MEDIUM,

  // 高嚴重程度
  [ERROR_CODES.TOKEN_EXPIRED]: ERROR_SEVERITY.HIGH,
  [ERROR_CODES.TOKEN_INVALID]: ERROR_SEVERITY.HIGH,
  [ERROR_CODES.ACCESS_DENIED]: ERROR_SEVERITY.HIGH,
  [ERROR_CODES.DATABASE_QUERY_FAILED]: ERROR_SEVERITY.HIGH,
  [ERROR_CODES.DATABASE_TRANSACTION_FAILED]: ERROR_SEVERITY.HIGH,
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: ERROR_SEVERITY.HIGH,
  [ERROR_CODES.GEMINI_CLI_ERROR]: ERROR_SEVERITY.HIGH,
  [ERROR_CODES.GEMINI_CLI_TIMEOUT]: ERROR_SEVERITY.HIGH,
  [ERROR_CODES.NETWORK_ERROR]: ERROR_SEVERITY.HIGH,
  [ERROR_CODES.CONNECTION_TIMEOUT]: ERROR_SEVERITY.HIGH,

  // 致命嚴重程度
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: ERROR_SEVERITY.CRITICAL,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: ERROR_SEVERITY.CRITICAL,
  [ERROR_CODES.CONFIGURATION_ERROR]: ERROR_SEVERITY.CRITICAL,
  [ERROR_CODES.DATABASE_CONNECTION_FAILED]: ERROR_SEVERITY.CRITICAL,
  [ERROR_CODES.DATABASE_TIMEOUT]: ERROR_SEVERITY.CRITICAL,
  [ERROR_CODES.GEMINI_CLI_NOT_AVAILABLE]: ERROR_SEVERITY.CRITICAL,
  [ERROR_CODES.CONNECTION_REFUSED]: ERROR_SEVERITY.CRITICAL,
  [ERROR_CODES.UNKNOWN_ERROR]: ERROR_SEVERITY.CRITICAL
};

/**
 * HTTP 狀態碼映射
 */
export const ERROR_CODE_TO_HTTP_STATUS = {
  // 4xx 客戶端錯誤
  [ERROR_CODES.VALIDATION_FAILED]: 400,
  [ERROR_CODES.INVALID_INPUT]: 400,
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,
  [ERROR_CODES.INVALID_FORMAT]: 400,
  [ERROR_CODES.INPUT_TOO_LONG]: 400,
  [ERROR_CODES.INPUT_TOO_SHORT]: 400,
  [ERROR_CODES.INVALID_PARAMETER]: 400,
  
  [ERROR_CODES.AUTHENTICATION_FAILED]: 401,
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.TOKEN_INVALID]: 401,
  [ERROR_CODES.SESSION_EXPIRED]: 401,
  [ERROR_CODES.WEBSOCKET_AUTHENTICATION_FAILED]: 401,
  
  [ERROR_CODES.AUTHORIZATION_FAILED]: 403,
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,
  [ERROR_CODES.ACCESS_DENIED]: 403,
  
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODES.ENDPOINT_NOT_FOUND]: 404,
  [ERROR_CODES.FILE_NOT_FOUND]: 404,
  
  [ERROR_CODES.RESOURCE_CONFLICT]: 409,
  [ERROR_CODES.DUPLICATE_ENTRY]: 409,
  [ERROR_CODES.OPERATION_CONFLICT]: 409,
  
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
  [ERROR_CODES.REQUEST_QUOTA_EXCEEDED]: 429,
  [ERROR_CODES.GEMINI_CLI_RATE_LIMITED]: 429,

  // 5xx 伺服器錯誤
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODES.CONFIGURATION_ERROR]: 500,
  [ERROR_CODES.DATABASE_QUERY_FAILED]: 500,
  [ERROR_CODES.DATABASE_TRANSACTION_FAILED]: 500,
  [ERROR_CODES.DATABASE_CONSTRAINT_VIOLATION]: 500,
  [ERROR_CODES.WEBSOCKET_CONNECTION_FAILED]: 500,
  [ERROR_CODES.WEBSOCKET_SEND_FAILED]: 500,
  [ERROR_CODES.UNKNOWN_ERROR]: 500,
  
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.MAINTENANCE_MODE]: 503,
  [ERROR_CODES.DATABASE_CONNECTION_FAILED]: 503,
  [ERROR_CODES.DATABASE_TIMEOUT]: 503,
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 503,
  [ERROR_CODES.GEMINI_CLI_ERROR]: 503,
  [ERROR_CODES.GEMINI_CLI_NOT_AVAILABLE]: 503,
  [ERROR_CODES.CONNECTION_REFUSED]: 503,
  
  [ERROR_CODES.GEMINI_CLI_TIMEOUT]: 504,
  [ERROR_CODES.CONNECTION_TIMEOUT]: 504,
  [ERROR_CODES.NETWORK_ERROR]: 504,
  [ERROR_CODES.DNS_RESOLUTION_FAILED]: 504,
  
  [ERROR_CODES.GEMINI_CLI_AUTH_FAILED]: 502
};

/**
 * 用戶友好的錯誤訊息
 */
export const USER_FRIENDLY_MESSAGES = {
  [ERROR_CODES.VALIDATION_FAILED]: '輸入資料驗證失敗，請檢查您的輸入',
  [ERROR_CODES.INVALID_INPUT]: '輸入格式不正確',
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: '缺少必填欄位',
  [ERROR_CODES.INVALID_FORMAT]: '輸入格式無效',
  [ERROR_CODES.INPUT_TOO_LONG]: '輸入內容過長',
  [ERROR_CODES.INPUT_TOO_SHORT]: '輸入內容過短',
  [ERROR_CODES.INVALID_PARAMETER]: '參數無效',
  
  [ERROR_CODES.AUTHENTICATION_FAILED]: '身份驗證失敗',
  [ERROR_CODES.INVALID_CREDENTIALS]: '帳號或密碼錯誤',
  [ERROR_CODES.TOKEN_EXPIRED]: '登入狀態已過期，請重新登入',
  [ERROR_CODES.TOKEN_INVALID]: '登入狀態無效，請重新登入',
  [ERROR_CODES.SESSION_EXPIRED]: '會話已過期，請重新登入',
  
  [ERROR_CODES.AUTHORIZATION_FAILED]: '權限不足',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: '權限不足，無法執行此操作',
  [ERROR_CODES.ACCESS_DENIED]: '拒絕存取',
  
  [ERROR_CODES.RESOURCE_NOT_FOUND]: '找不到請求的資源',
  [ERROR_CODES.ENDPOINT_NOT_FOUND]: '找不到請求的端點',
  [ERROR_CODES.FILE_NOT_FOUND]: '找不到檔案',
  
  [ERROR_CODES.RESOURCE_CONFLICT]: '資源衝突',
  [ERROR_CODES.DUPLICATE_ENTRY]: '資料重複',
  [ERROR_CODES.OPERATION_CONFLICT]: '操作衝突',
  
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: '請求過於頻繁，請稍後再試',
  [ERROR_CODES.TOO_MANY_REQUESTS]: '請求次數過多',
  [ERROR_CODES.REQUEST_QUOTA_EXCEEDED]: '請求配額已超過',
  
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: '內部伺服器錯誤',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: '服務暫時無法使用',
  [ERROR_CODES.CONFIGURATION_ERROR]: '伺服器配置錯誤',
  [ERROR_CODES.MAINTENANCE_MODE]: '系統維護中',
  
  [ERROR_CODES.DATABASE_CONNECTION_FAILED]: '資料庫連接失敗',
  [ERROR_CODES.DATABASE_QUERY_FAILED]: '資料查詢失敗',
  [ERROR_CODES.DATABASE_TRANSACTION_FAILED]: '資料庫事務失敗',
  [ERROR_CODES.DATABASE_CONSTRAINT_VIOLATION]: '資料約束違反',
  [ERROR_CODES.DATABASE_TIMEOUT]: '資料庫操作超時',
  
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: '外部服務錯誤',
  [ERROR_CODES.GEMINI_CLI_ERROR]: 'Gemini CLI 服務錯誤',
  [ERROR_CODES.GEMINI_CLI_TIMEOUT]: 'Gemini CLI 請求超時',
  [ERROR_CODES.GEMINI_CLI_NOT_AVAILABLE]: 'Gemini CLI 服務不可用',
  [ERROR_CODES.GEMINI_CLI_AUTH_FAILED]: 'Gemini CLI 認證失敗',
  [ERROR_CODES.GEMINI_CLI_RATE_LIMITED]: 'Gemini CLI 請求頻率受限',
  
  [ERROR_CODES.NETWORK_ERROR]: '網路連接錯誤',
  [ERROR_CODES.CONNECTION_TIMEOUT]: '連接超時',
  [ERROR_CODES.CONNECTION_REFUSED]: '連接被拒絕',
  [ERROR_CODES.DNS_RESOLUTION_FAILED]: 'DNS 解析失敗',
  
  [ERROR_CODES.WEBSOCKET_CONNECTION_FAILED]: 'WebSocket 連接失敗',
  [ERROR_CODES.WEBSOCKET_SEND_FAILED]: 'WebSocket 發送失敗',
  [ERROR_CODES.WEBSOCKET_AUTHENTICATION_FAILED]: 'WebSocket 認證失敗',
  
  [ERROR_CODES.UNKNOWN_ERROR]: '未知錯誤'
};